import  argparse

args = argparse.ArgumentParser()

args.add_argument('--method', type=str, default='TD3', help='method')
args.add_argument('--dataset-name', type=str, default='tiny', help='specify a dataset')
args.add_argument('--training-mode', type=str, default='train', help='train or evaluate')
args.add_argument('--params', type=str, default='', help='load existing parameters')
args.add_argument('--memory', type=str, default='', help='add replay memory')
args.add_argument('--noisy', action='store_true', help='use noisy linear layer')
args.add_argument('--batch-size', type=int, default=128, help='training batch size')
args.add_argument('--epoches', type=int, default=8000, help='training epoches')
args.add_argument('--test-epoches', type=int, default=250, help='online tuning Epoches')
args.add_argument('--pec-reward', type=float, default=1)
args.add_argument('--alr', type=float, default=0.00001)
args.add_argument('--clr', type=float, default=0.0001)
args.add_argument('--tau', type=float, default=0.0001)
args.add_argument('--n-states', type=int, default=12, help='n_states')
args.add_argument('--n-actions', type=int, default=3, help='n_actions')
args.add_argument('--n-states_nsg', type=int, default=18, help='n_states')
args.add_argument('--n-actions-nsg', type=int, default=6, help='n_actions')
args.add_argument('--sigma-decay-rate', type=float, default=0.98)
args.add_argument('--sigma', type=float, default=0.2)
args.add_argument('--sigma-value', type=float, default=0.2)
args.add_argument('--policy-noise-clip', type=float, default=0.2)
args.add_argument('--delay-time', type=int, default=2)
args.add_argument('--memory-size', type=int, default=100000, help='memory_size')
args.add_argument('--max-steps', type=int, default=5000, help='max_steps')
args.add_argument('--nochange-steps', type=int, default=200, help='max_nochange_steps')
args.add_argument('--nochange-episodes', type=int, default=150, help='max_nochange_episodes')
args.add_argument('--actor-layer-sizes', type=str, default='[128, 256, 256, 64]')
args.add_argument('--critic-layer-sizes', type=str, default='[256, 256, 256, 64]')
args.add_argument('--seed', type=int, default=42)

args, unknown = args.parse_known_args()

